import Head from "next/head";

export interface MetaProps {}

export const Meta = ({}: MetaProps) => {
  return (
    <Head>
      <title>ljtech Memory</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};
